FROM node:20-alpine

WORKDIR /app

# Install deps
COPY frontend/package*.json ./
RUN npm install

# Copy app
COPY frontend .

ENV NEXT_PUBLIC_API_URL=http://localhost:8000/api
EXPOSE 3000

CMD ["npm", "run", "dev", "--", "-H", "0.0.0.0", "-p", "3000"]
